movie_df = data[data['type'] == 'Movie'].copy()
# movie_df['duration_int'] =movie_df['duration'].str.replace(' min', '').astype(int)
# plt.figure(figsize=(10,6))
# plt.hist(movie_df['duration_int'], bins=8, color='coral', edgecolor='black')
# # plt.hist(movie_df['duration_int'], bins=15, color='coral', edgecolor='black', alpha=0.8)

# plt.title('Distribution of Movie Durations on Netflix')
# plt.xlabel('Duration (minutes)')
# plt.ylabel('Number of Movies')
# plt.tight_layout()
# plt.savefig('movie_durationhistogram.png')
# plt.show()